services:
  postgres:
    container_name: container-pg
    image: postgres:16
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - C:\Users\a.zolotarev\Desktop\postgres\demodb:/scripts
    restart: unless-stopped
    
volumes:
  postgres-data: