drop table accounts;

CREATE TABLE accounts(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  number text UNIQUE,
  client text,
  amount numeric
);
INSERT INTO accounts values (1, '1001', 'alice', 1000.00), (2, '2001', 'bob', 100.00), (3, '2002', 'bob', 900.00);

begin transaction;
//1
UPDATE accounts SET amount = amount - 100 WHERE id = 2;
//3
UPDATE accounts SET amount = amount + 100 WHERE id = 3;
//4
COMMIT;

begin transaction;
//2
SELECT amount FROM accounts WHERE id = 2;
//5
SELECT amount FROM accounts WHERE id = 3;

amount will be 1000:)
