drop table accounts;

CREATE TABLE accounts(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  number text UNIQUE,
  client text,
  amount numeric
);
INSERT INTO accounts values (1, '1001', 'alice', 1000.00), (2, '2001', 'bob', 100.00), (3, '2002', 'bob', 900.00);

begin transaction;
//1
UPDATE accounts SET amount = amount - 100 WHERE id = 3;
//3
commit;


begin transaction;
//2
UPDATE accounts SET amount = amount * 1.01 WHERE client IN (SELECT client FROM accounts GROUP BY client HAVING sum(amount) >= 1000);
//4
SELECT * FROM accounts WHERE client = 'bob';
commit;

//will be 101, 808