drop table accounts;

CREATE TABLE accounts(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  number text UNIQUE,
  client text,
  amount numeric
);
INSERT INTO accounts values (1, '1001', 'alice', 1000.00), (2, '2001', 'bob', 100.00), (3, '2002', 'bob', 900.00);


//1
SELECT amount, pg_sleep(2) FROM accounts WHERE client = 'bob';

//will be 100 and 900 correct

//2
begin transaction;
UPDATE accounts SET amount = amount + 100 WHERE id = 2;
UPDATE accounts SET amount = amount - 100 WHERE id = 3;
COMMIT;


//volatile 
drop function get_amount;
CREATE FUNCTION get_amount(id integer) RETURNS numeric AS $$
  SELECT amount FROM accounts a WHERE a.id = get_amount.id;
$$ VOLATILE LANGUAGE sql;


//1
SELECT amount, pg_sleep(2) FROM accounts WHERE client = 'bob';
// it will be 100, 800 incorrect we have got incosistent data

//2
begin transaction;
UPDATE accounts SET amount = amount + 100 WHERE id = 2;
UPDATE accounts SET amount = amount - 100 WHERE id = 3;
COMMIT;

//we can solve this by STABLE keyword